# Introduction

```{r, include = FALSE}
suppressWarnings(suppressPackageStartupMessages({
  library(data.table)
  library(tidyverse)
  library(tidymodels)
  library(naniar)
  library(readxl)
  library(janitor)
  library(rmarkdown)
  library(knitr)
  library(kableExtra)
  library(modelsummary)
  library(DoubleML)
  library(mlr3)
  library(broom)
  library(sandwich)
  library(lmtest)
  library(mlr3learners)
  library(readr)
  library(MatchIt)
  library(ggplot2)
  library(dplyr)
  library(summarytools)
  library(DataExplorer)
  library(mlr3learners)
  library(mlr3measures)
  library(mlr3resampling) 
}))
set.seed(1111)
data010a <- rnorm(1000000)
hist(
  data010a,
  labels = TRUE,
  col = "grey",
  breaks = 100,
  main = "Histogram of Random Data",
  xlab = "Value",
  ylab = "Frequency"
)
rdx = rnorm(1000)
rdy = as.numeric(rdx > 0)
rdix = sample(1:1000, 100)
rdy[rdix] = 1 - rdy[rdix]
rdf = data.frame(rdx, rdy)
plot(rdf$rdx, rdf$rdy)
m <- glm(rdy ~ rdx, data = rdf, family = binomial())
xs <- seq(min(rdf$rdx), max(rdf$rdx), length.out = 300)
lines(
  xs,
  predict(m, newdata = data.frame(rdx = xs), type = "response"),
  lwd = 2
)
load("correctional_stats_report_environment1b.RData")
```

### A01-RC Detailed Dataset

```{r, echo = FALSE}
dataframe_original <- df
cols_to_rename <- setdiff(names(dataframe_original), "unique_individual_id")
num_to_letters <- function(n) {
  sapply(n, function(i) {
    out <- ""
    while (i > 0) {
      i <- i - 1
      out <- paste0(letters[(i %% 26) + 1], out)
      i <- i %/% 26
    }
    out
  })
}
new_names <- paste0("x1", num_to_letters(seq_along(cols_to_rename)))
names(dataframe_original)[match(cols_to_rename, names(dataframe_original))] <- new_names
knitr::kable(
  head(dataframe_original[, setdiff(names(dataframe_original), "unique_individual_id")], 10),
  booktabs = TRUE, longtable = TRUE,
  caption = "Ontario Restrictive Confinement Dataframe (2023-2025)")
```

```{r, echo = FALSE}
suppressWarnings(suppressPackageStartupMessages({
  library(data.table)
  library(tidyverse)
  library(tidymodels)
  library(naniar)
  library(readxl)
  library(janitor)
  library(rmarkdown)
  library(knitr)
  library(kableExtra)
  library(modelsummary)
  library(DoubleML)
  library(mlr3)
  library(broom)
  library(sandwich)
  library(lmtest)
  library(mlr3learners)
  library(readr)
  library(MatchIt)
  library(ggplot2)
  library(dplyr)
  library(summarytools)
  library(DataExplorer)
  library(mlr3learners)
  library(mlr3measures)
  library(mlr3resampling) 
}))
load("correctional_stats_report_environment1b.RData")
region_names <- c("Central", "Eastern", "Northern", "Toronto", "Western")
age_levels <- c("18 to 24", "25 to 49", "50+")
sex_levels <- c("Male", "Female")
years <- 2023:2025
df_rc <- as.data.table(df)
df_rc[, end_fiscal_year := as.integer(end_fiscal_year)]
df_rc[, age_category := factor(age_category, levels = age_levels)]
df_rc[, gender := factor(gender, levels = sex_levels)]
df_rc[,
  region_at_time_of_placement := factor(
    region_at_time_of_placement,
    levels = region_names
  )
]
get_region_by_age <- function(D, yr, sex = NULL) {
  tmp <- D[
    end_fiscal_year == yr &
      !is.na(age_category) &
      !is.na(region_at_time_of_placement)
  ]
  if (!is.null(sex)) {
    tmp <- tmp[gender == sex]
  }
  tab <- tmp[,
    .(n = uniqueN(unique_individual_id)),
    by = .(age_category, region_at_time_of_placement)
  ]
  grid <- CJ(
    age_category = age_levels,
    region_at_time_of_placement = region_names,
    unique = TRUE
  )
  tab <- merge(
    grid,
    tab,
    by = c("age_category", "region_at_time_of_placement"),
    all.x = TRUE
  )
  tab[is.na(n), n := 0L]
  wide <- dcast(
    tab,
    age_category ~ region_at_time_of_placement,
    value.var = "n"
  )
  S <- as.matrix(wide[, -1])
  rownames(S) <- wide$age_category
  den <- rowSums(S)
  P <- sweep(S, 1, den, "/")
  P[den == 0, ] <- NA_real_
  list(S = S, P = P)
}
P_year <- list()
S_year <- list()
for (yr in years) {
  out_all <- get_region_by_age(df_rc, yr)
  P <- out_all$P
  S_year[[as.character(yr)]] <- out_all$S
  P_year[[as.character(yr)]] <- P
  cols <- seq_len(ncol(P))
  matplot(
    P,
    type = "l",
    lwd = 2,
    lty = 1,
    col = cols,
    xaxt = "n",
    xlab = "Age Group",
    ylab = "Proportion",
    main = paste0(yr, " Region at Time of Placement by Age Group")
  )
  axis(1, at = seq_len(nrow(P)), labels = rownames(P))
  legend(
    "topright",
    legend = colnames(P),
    col = cols,
    lty = 1,
    lwd = 2,
    bty = "n"
  )
  par(mfrow = c(1, 2), mar = c(4, 4, 3, 1))
  for (sex in c("Male", "Female")) {
    out_sex <- get_region_by_age(df_rc, yr, sex = sex)
    Psex <- out_sex$P
    cols <- seq_len(ncol(Psex))
    matplot(
      Psex,
      type = "l",
      lwd = 2,
      lty = 1,
      col = cols,
      xaxt = "n",
      xlab = "Age Group",
      ylab = "Proportion",
      main = paste0(yr, " RTP (", sex, ")")
    )
    axis(1, at = seq_len(nrow(Psex)), labels = rownames(Psex))
    legend(
      "topright",
      legend = colnames(Psex),
      col = cols,
      lty = 1,
      lwd = 2,
      bty = "n"
    )
  }
  par(mfrow = c(1, 1))
}
```
